spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wiki?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver