spring:
  datasource:
    url: jdbc:mysql://localhost:3306/statadata?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  elasticsearch:
    uris: http://localhost:9200
    UserName: elastic #账号
    Password: ilTvMR8ZRTZBtFNg_w3z #你的elasticsearch密码
server :
  port : 8080
